import HomeLevelPage from "@/app/components/HomePage/HomeLevelPage";
import CalculateIcon from "@mui/icons-material/Calculate";
import BookIcon from "@mui/icons-material/Book";
import LanguageIcon from "@mui/icons-material/Language";
import ScienceIcon from "@mui/icons-material/Science";
import BrushIcon from "@mui/icons-material/Brush";
import SportsSoccerIcon from "@mui/icons-material/SportsSoccer";
import MusicNoteIcon from "@mui/icons-material/MusicNote";
import PsychologyIcon from "@mui/icons-material/Psychology";
import FavoriteIcon from "@mui/icons-material/Favorite";
import EngineeringIcon from "@mui/icons-material/Engineering";

export default function SecundariaPage() {
  const gradesContent = {
    "1roS": {
      title: "Primer Año Secundaria",
      subtitle: "Iniciando la educación secundaria",
      objetivos: [
        { titulo: "Adaptación", descripcion: "Fomentar hábitos de estudio y organización personal." },
        { titulo: "Exploración", descripcion: "Motivar la curiosidad por distintas áreas académicas." },
      ],
      materias: [
        { Materia: "Lengua castellana y originaria", Horas: "24 h/mes", color: "#c62828", Icono: BookIcon,
          temas: ["Redacción de textos", "Comprensión lectora", "Gramática básica"] },
        { Materia: "Lengua extranjera", Horas: "8 h/mes", color: "#f57c00", Icono: LanguageIcon,
          temas: ["Vocabulario", "Lectura básica", "Expresión oral"] },
        { Materia: "Ciencias Sociales", Horas: "12 h/mes", color: "#6a1b9a", Icono: BookIcon,
          temas: ["Historia de Bolivia", "Geografía local", "Cultura y sociedad"] },
        { Materia: "Artes Plásticas", Horas: "8 h/mes", color: "#ff9800", Icono: BrushIcon,
          temas: ["Dibujo", "Pintura", "Expresión creativa"] },
        { Materia: "Educación Física", Horas: "8 h/mes", color: "#2e7d32", Icono: SportsSoccerIcon,
          temas: ["Juegos y coordinación", "Deportes recreativos"] },
        { Materia: "Educación Musical", Horas: "8 h/mes", color: "#e91e63", Icono: MusicNoteIcon,
          temas: ["Instrumentos básicos", "Canto", "Ritmo"] },
        { Materia: "Matemáticas", Horas: "20 h/mes", color: "#1976d2", Icono: CalculateIcon,
          temas: ["Números enteros", "Fracciones", "Geometría básica"] },
        { Materia: "Técnica Tecnológica", Horas: "16 h/mes", color: "#455a64", Icono: EngineeringIcon,
          temas: ["Introducción a la robótica", "Diseño y prototipos", "Herramientas digitales"] },
        { Materia: "Biología y Geografía", Horas: "16 h/mes", color: "#43a047", Icono: ScienceIcon,
          temas: ["Seres vivos", "Ecosistemas", "Geografía física"] },
        { Materia: "Filosofía y Psicología", Horas: "8 h/mes", color: "#9c27b0", Icono: PsychologyIcon,
          temas: ["Autoconocimiento", "Valores personales", "Reflexión ética"] },
        { Materia: "Valores y Religión", Horas: "8 h/mes", color: "#ff5722", Icono: FavoriteIcon,
          temas: ["Respeto y tolerancia", "Solidaridad", "Ética básica"] },
      ],
    },
    "2doS": {
      title: "Segundo Año Secundaria",
      subtitle: "Desarrollo de habilidades académicas y sociales",
      objetivos: [
        { titulo: "Razonamiento", descripcion: "Desarrollar pensamiento crítico y autónomo." },
        { titulo: "Participación", descripcion: "Fomentar responsabilidad y cooperación en clase." },
      ],
      materias: [
        { Materia: "Lengua castellana y originaria", Horas: "24 h/mes", color: "#c62828", Icono: BookIcon,
          temas: ["Análisis literario", "Redacción avanzada", "Ortografía"] },
        { Materia: "Lengua extranjera", Horas: "8 h/mes", color: "#f57c00", Icono: LanguageIcon,
          temas: ["Conversación básica", "Gramática", "Lectura crítica"] },
        { Materia: "Ciencias Sociales", Horas: "12 h/mes", color: "#6a1b9a", Icono: BookIcon,
          temas: ["Historia contemporánea", "Geografía regional", "Cultura y ciudadanía"] },
        { Materia: "Artes Plásticas", Horas: "8 h/mes", color: "#ff9800", Icono: BrushIcon,
          temas: ["Técnicas mixtas", "Diseño artístico", "Proyectos creativos"] },
        { Materia: "Educación Física", Horas: "8 h/mes", color: "#2e7d32", Icono: SportsSoccerIcon,
          temas: ["Deportes reglamentados", "Condición física", "Trabajo en equipo"] },
        { Materia: "Educación Musical", Horas: "8 h/mes", color: "#e91e63", Icono: MusicNoteIcon,
          temas: ["Instrumentos musicales", "Coro y armonía", "Historia de la música"] },
        { Materia: "Matemáticas", Horas: "20 h/mes", color: "#1976d2", Icono: CalculateIcon,
          temas: ["Álgebra básica", "Geometría", "Problemas prácticos"] },
        { Materia: "Técnica Tecnológica", Horas: "16 h/mes", color: "#455a64", Icono: EngineeringIcon,
          temas: ["Proyectos tecnológicos", "Robótica básica", "Diseño y prototipado"] },
        { Materia: "Biología y Geografía", Horas: "16 h/mes", color: "#43a047", Icono: ScienceIcon,
          temas: ["Ecosistemas y biodiversidad", "Climatología", "Fisiología básica"] },
        { Materia: "Filosofía y Psicología", Horas: "8 h/mes", color: "#9c27b0", Icono: PsychologyIcon,
          temas: ["Reflexión ética", "Valores y conducta", "Psicología básica"] },
        { Materia: "Valores y Religión", Horas: "8 h/mes", color: "#ff5722", Icono: FavoriteIcon,
          temas: ["Respeto y tolerancia", "Solidaridad y empatía", "Ética comunitaria"] },
      ],
    },
    "3roS": {
      title: "Tercer Año Secundaria",
      subtitle: "Consolidación de aprendizajes y habilidades",
      objetivos: [
        { titulo: "Pensamiento crítico", descripcion: "Analizar información de manera reflexiva y autónoma." },
        { titulo: "Creatividad", descripcion: "Desarrollar proyectos innovadores en distintas áreas." },
      ],
      materias: [
        { Materia: "Lengua castellana y originaria", Horas: "24 h/mes", color: "#c62828", Icono: BookIcon,
          temas: ["Literatura universal", "Redacción argumentativa", "Ortografía avanzada"] },
        { Materia: "Lengua extranjera", Horas: "8 h/mes", color: "#f57c00", Icono: LanguageIcon,
          temas: ["Conversación fluida", "Gramática avanzada", "Comprensión lectora"] },
        { Materia: "Ciencias Sociales", Horas: "20 h/mes", color: "#6a1b9a", Icono: BookIcon,
          temas: ["Historia mundial", "Geografía política", "Cultura y sociedad"] },
        { Materia: "Artes Plásticas", Horas: "8 h/mes", color: "#ff9800", Icono: BrushIcon,
          temas: ["Arte contemporáneo", "Diseño avanzado", "Proyecto artístico"] },
        { Materia: "Educación Física", Horas: "8 h/mes", color: "#2e7d32", Icono: SportsSoccerIcon,
          temas: ["Deportes competitivos", "Condición física avanzada", "Trabajo en equipo"] },
        { Materia: "Educación Musical", Horas: "8 h/mes", color: "#e91e63", Icono: MusicNoteIcon,
          temas: ["Orquesta y coro", "Composición musical", "Historia de la música"] },
        { Materia: "Matemáticas", Horas: "20 h/mes", color: "#1976d2", Icono: CalculateIcon,
          temas: ["Álgebra intermedia", "Geometría analítica", "Problemas complejos"] },
        { Materia: "Técnica Tecnológica", Horas: "32 h/mes", color: "#455a64", Icono: EngineeringIcon,
          temas: ["Robótica avanzada", "Programación aplicada", "Diseño de prototipos funcionales"] },
        { Materia: "Biología y Geografía", Horas: "16 h/mes", color: "#43a047", Icono: ScienceIcon,
          temas: ["Fisiología humana", "Ecosistemas complejos", "Geografía mundial"] },
        { Materia: "Física", Horas: "8 h/mes", color: "#1976d2", Icono: ScienceIcon,
          temas: ["Mecánica", "Leyes de Newton", "Estática y dinámica"] },
        { Materia: "Química", Horas: "8 h/mes", color: "#ff5722", Icono: ScienceIcon,
          temas: ["Propiedades de la materia", "Reacciones químicas", "Elementos y compuestos"] },
        { Materia: "Filosofía y Psicología", Horas: "8 h/mes", color: "#9c27b0", Icono: PsychologyIcon,
          temas: ["Ética y moral", "Identidad personal", "Psicología del adolescente"] },
        { Materia: "Valores y Religión", Horas: "8 h/mes", color: "#ff5722", Icono: FavoriteIcon,
          temas: ["Ética social", "Respeto y tolerancia", "Solidaridad activa"] },
      ],
    },
    "4toS": {
      title: "Cuarto Año Secundaria",
      subtitle: "Profundización académica y orientación vocacional",
      objetivos: [
        { titulo: "Análisis avanzado", descripcion: "Comprender y aplicar conceptos complejos." },
        { titulo: "Orientación", descripcion: "Explorar intereses vocacionales y profesionales." },
      ],
      materias: [
        { Materia: "Lengua castellana y originaria", Horas: "20 h/mes", color: "#c62828", Icono: BookIcon,
          temas: ["Literatura boliviana", "Ensayo y composición", "Análisis gramatical avanzado"] },
        { Materia: "Lengua extranjera", Horas: "10 h/mes", color: "#f57c00", Icono: LanguageIcon,
          temas: ["Lectura crítica", "Expresión escrita", "Conversación avanzada"] },
        { Materia: "Ciencias Sociales", Horas: "24 h/mes", color: "#6a1b9a", Icono: BookIcon,
          temas: ["Historia contemporánea", "Geopolítica", "Economía básica"] },
        { Materia: "Artes Plásticas", Horas: "10 h/mes", color: "#ff9800", Icono: BrushIcon,
          temas: ["Técnicas artísticas avanzadas", "Proyecto creativo personal"] },
        { Materia: "Educación Física", Horas: "10 h/mes", color: "#2e7d32", Icono: SportsSoccerIcon,
          temas: ["Deportes competitivos", "Preparación física avanzada"] },
        { Materia: "Educación Musical", Horas: "8 h/mes", color: "#e91e63", Icono: MusicNoteIcon,
          temas: ["Música aplicada", "Composición y arreglos"] },
        { Materia: "Matemáticas", Horas: "22 h/mes", color: "#1976d2", Icono: CalculateIcon,
          temas: ["Álgebra avanzada", "Trigonometría", "Geometría analítica"] },
        { Materia: "Física", Horas: "10 h/mes", color: "#1976d2", Icono: ScienceIcon,
          temas: ["Electricidad", "Mecánica avanzada", "Termodinámica básica"] },
        { Materia: "Química", Horas: "10 h/mes", color: "#ff5722", Icono: ScienceIcon,
          temas: ["Química inorgánica", "Reacciones y compuestos", "Experimentos guiados"] },
        { Materia: "Biología", Horas: "16 h/mes", color: "#43a047", Icono: ScienceIcon,
          temas: ["Genética básica", "Ecología", "Anatomía y fisiología"] },
        { Materia: "Técnica Tecnológica", Horas: "32 h/mes", color: "#455a64", Icono: EngineeringIcon,
          temas: ["Robótica avanzada", "Programación aplicada", "Proyectos tecnológicos"] },
        { Materia: "Filosofía y Psicología", Horas: "8 h/mes", color: "#9c27b0", Icono: PsychologyIcon,
          temas: ["Ética y sociedad", "Toma de decisiones", "Psicología aplicada"] },
        { Materia: "Valores y Religión", Horas: "8 h/mes", color: "#ff5722", Icono: FavoriteIcon,
          temas: ["Ética y convivencia", "Respeto y tolerancia", "Solidaridad"] },
      ],
    },
    "5toS": {
      title: "Quinto Año Secundaria",
      subtitle: "Preparación académica avanzada y vocacional",
      objetivos: [
        { titulo: "Profundización", descripcion: "Aplicar conocimientos avanzados en diversas áreas." },
        { titulo: "Proyecto personal", descripcion: "Iniciar proyectos de investigación o desarrollo personal." },
      ],
      materias: [
        { Materia: "Lengua castellana y originaria", Horas: "20 h/mes", color: "#c62828", Icono: BookIcon,
          temas: ["Literatura contemporánea", "Redacción académica", "Análisis textual avanzado"] },
        { Materia: "Lengua extranjera", Horas: "10 h/mes", color: "#f57c00", Icono: LanguageIcon,
          temas: ["Comprensión oral avanzada", "Expresión escrita", "Lectura crítica"] },
        { Materia: "Ciencias Sociales", Horas: "24 h/mes", color: "#6a1b9a", Icono: BookIcon,
          temas: ["Historia global", "Economía aplicada", "Geopolítica"] },
        { Materia: "Artes Plásticas", Horas: "10 h/mes", color: "#ff9800", Icono: BrushIcon,
          temas: ["Proyecto artístico personal", "Diseño y técnicas avanzadas"] },
        { Materia: "Educación Física", Horas: "10 h/mes", color: "#2e7d32", Icono: SportsSoccerIcon,
          temas: ["Preparación física avanzada", "Deportes competitivos"] },
        { Materia: "Educación Musical", Horas: "8 h/mes", color: "#e91e63", Icono: MusicNoteIcon,
          temas: ["Composición musical", "Historia de la música avanzada"] },
        { Materia: "Matemáticas", Horas: "22 h/mes", color: "#1976d2", Icono: CalculateIcon,
          temas: ["Cálculo básico", "Álgebra avanzada", "Estadística introductoria"] },
        { Materia: "Física", Horas: "10 h/mes", color: "#1976d2", Icono: ScienceIcon,
          temas: ["Electricidad y magnetismo", "Mecánica avanzada"] },
        { Materia: "Química", Horas: "10 h/mes", color: "#ff5722", Icono: ScienceIcon,
          temas: ["Química orgánica", "Experimentos guiados"] },
        { Materia: "Biología", Horas: "16 h/mes", color: "#43a047", Icono: ScienceIcon,
          temas: ["Genética avanzada", "Ecología aplicada", "Fisiología avanzada"] },
        { Materia: "Técnica Tecnológica", Horas: "32 h/mes", color: "#455a64", Icono: EngineeringIcon,
          temas: ["Proyectos de ingeniería", "Programación avanzada", "Robótica aplicada"] },
        { Materia: "Filosofía y Psicología", Horas: "8 h/mes", color: "#9c27b0", Icono: PsychologyIcon,
          temas: ["Ética avanzada", "Psicología aplicada", "Toma de decisiones"] },
        { Materia: "Valores y Religión", Horas: "8 h/mes", color: "#ff5722", Icono: FavoriteIcon,
          temas: ["Ética social avanzada", "Convivencia responsable"] },
      ],
    },
    "6toS": {
      title: "Sexto Año Secundaria",
      subtitle: "Cierre de la secundaria y preparación universitaria",
      objetivos: [
        { titulo: "Síntesis", descripcion: "Integrar todos los conocimientos adquiridos." },
        { titulo: "Proyección", descripcion: "Orientación vocacional y preparación para estudios superiores." },
      ],
      materias: [
        { Materia: "Lengua castellana y originaria", Horas: "20 h/mes", color: "#c62828", Icono: BookIcon,
          temas: ["Análisis literario avanzado", "Redacción académica", "Preparación para la universidad"] },
        { Materia: "Lengua extranjera", Horas: "10 h/mes", color: "#f57c00", Icono: LanguageIcon,
          temas: ["Comprensión oral y escrita avanzada", "Expresión académica", "Lectura crítica"] },
        { Materia: "Ciencias Sociales", Horas: "24 h/mes", color: "#6a1b9a", Icono: BookIcon,
          temas: ["Historia universal", "Geopolítica avanzada", "Economía y ciudadanía"] },
        { Materia: "Artes Plásticas", Horas: "10 h/mes", color: "#ff9800", Icono: BrushIcon,
          temas: ["Portafolio artístico personal", "Proyectos creativos avanzados"] },
        { Materia: "Educación Física", Horas: "10 h/mes", color: "#2e7d32", Icono: SportsSoccerIcon,
          temas: ["Deportes avanzados", "Preparación física integral"] },
        { Materia: "Educación Musical", Horas: "8 h/mes", color: "#e91e63", Icono: MusicNoteIcon,
          temas: ["Composición y arreglos", "Historia de la música avanzada"] },
        { Materia: "Matemáticas", Horas: "24 h/mes", color: "#1976d2", Icono: CalculateIcon,
          temas: ["Cálculo", "Estadística", "Geometría avanzada"] },
        { Materia: "Física", Horas: "12 h/mes", color: "#1976d2", Icono: ScienceIcon,
          temas: ["Mecánica avanzada", "Electricidad y magnetismo", "Ondas y energía"] },
        { Materia: "Química", Horas: "12 h/mes", color: "#ff5722", Icono: ScienceIcon,
          temas: ["Química orgánica y analítica", "Laboratorio avanzado"] },
        { Materia: "Biología", Horas: "16 h/mes", color: "#43a047", Icono: ScienceIcon,
          temas: ["Genética avanzada", "Biotecnología", "Fisiología compleja"] },
        { Materia: "Técnica Tecnológica", Horas: "32 h/mes", color: "#455a64", Icono: EngineeringIcon,
          temas: ["Proyectos tecnológicos finales", "Robótica avanzada", "Programación aplicada"] },
        { Materia: "Filosofía y Psicología", Horas: "8 h/mes", color: "#9c27b0", Icono: PsychologyIcon,
          temas: ["Ética y moral avanzada", "Psicología del joven adulto"] },
        { Materia: "Valores y Religión", Horas: "8 h/mes", color: "#ff5722", Icono: FavoriteIcon,
          temas: ["Ética social y personal", "Respeto y responsabilidad ciudadana"] },
      ],
    },
  };

  return (
    <HomeLevelPage
      levelTitle="Plan de estudios - Nivel Secundaria"
      levelDescription="Formación académica integral para adolescentes de 12 a 18 años"
      gradesContent={gradesContent}
      toggleLabels={[
        "1ro Secundaria",
        "2do Secundaria",
        "3ro Secundaria",
        "4to Secundaria",
        "5to Secundaria",
        "6to Secundaria",
      ]}
    />
  );
}
